Add ignorePaths setting
remotely-save/remotely-save pull request #414
Opened 2023-12-29 12:49 UTC by ras0q

close #163

### Feature

This PR adds a `ignorePaths` setting. `ignorePaths` setting allows you to specify files or folders that you want to exclude from syncing. This feature is especially helpful when the option `Sync Config Dir (experimental)` is enabled.

### What Changed

- [x] add a `ignorePaths` setting
  - default is `[".obsidian/workspace.json", ".obsidian/workspace-mobile.json", ".obsidian/community-plugins.json"]`
- [x] add an Obsidian setting option
  - One path per line
  - ![image](https://github.com/remotely-save/remotely-save/assets/66677201/eb3ec939-6dca-4319-a239-4507aad53abc)
- [x] add i18n keys
  - `settings_ignorepaths` and `settings_ignorepaths_desc`
  - see https://github.com/remotely-save/langs/pull/4
  - I have no knoqledge of Chinese, so I would like you to correct the values if their are incorrect. :pray:
- [ ] add tests
  - where should I write tests ?

2024-01-01 11:06 UTC, da-the-dev approved these changes

2024-01-01 11:43 UTC, da-the-dev commented on src/settings.ts
> +      .setDesc(t("settings_ignorepaths_desc"))
I don't know if I'm doing it right, but if if I try to `npm run build` with your changes, I get:
```
ERROR in /home/sv-cheats-1/Documents/PROJECTS/remotely-save/src/settings.ts
./src/settings.ts 1600:17-39
[tsl] ERROR in /home/sv-cheats-1/Documents/PROJECTS/remotely-save/src/settings.ts(1600,18)
      TS2345: Argument of type '"settings_ignorepaths"' is not assignable to parameter of type '"confirm" | "disable" | "enable" | "goback" | 
"submit" | "sometext" | "syncrun_alreadyrunning" | "syncrun_syncingribbon" | "syncrun_step0" | "syncrun_step1" | "syncrun_step2" | ... 230 mor
e ... | "syncalgov2_button_disagree"'.
ts-loader-default_e3b0c44298fc1c14
 @ ./src/main.ts 13:0-52 415:35-57

ERROR in /home/sv-cheats-1/Documents/PROJECTS/remotely-save/src/settings.ts
./src/settings.ts 1601:17-44
[tsl] ERROR in /home/sv-cheats-1/Documents/PROJECTS/remotely-save/src/settings.ts(1601,18)
      TS2345: Argument of type '"settings_ignorepaths_desc"' is not assignable to parameter of type '"confirm" | "disable" | "enable" | "gobac
k" | "submit" | "sometext" | "syncrun_alreadyrunning" | "syncrun_syncingribbon" | "syncrun_step0" | "syncrun_step1" | "syncrun_step2" | ... 23
0 more ... | "syncalgov2_button_disagree"'.
ts-loader-default_e3b0c44298fc1c14
 @ ./src/main.ts 13:0-52 415:35-57
```
Seems like there's a type issue in `settings.ts` that does not seem to like the new `settings_ignorepaths` field

2024-01-01 11:44 UTC, da-the-dev requested changes
I don't know if I'm doing it right, but if if I try to `npm run build` with your changes, I get:
```
ERROR in /home/sv-cheats-1/Documents/PROJECTS/remotely-save/src/settings.ts
./src/settings.ts 1600:17-39
[tsl] ERROR in /home/sv-cheats-1/Documents/PROJECTS/remotely-save/src/settings.ts(1600,18)
      TS2345: Argument of type '"settings_ignorepaths"' is not assignable to parameter of type '"confirm" | "disable" | "enable" | "goback" | 
"submit" | "sometext" | "syncrun_alreadyrunning" | "syncrun_syncingribbon" | "syncrun_step0" | "syncrun_step1" | "syncrun_step2" | ... 230 mor
e ... | "syncalgov2_button_disagree"'.
ts-loader-default_e3b0c44298fc1c14
 @ ./src/main.ts 13:0-52 415:35-57

ERROR in /home/sv-cheats-1/Documents/PROJECTS/remotely-save/src/settings.ts
./src/settings.ts 1601:17-44
[tsl] ERROR in /home/sv-cheats-1/Documents/PROJECTS/remotely-save/src/settings.ts(1601,18)
      TS2345: Argument of type '"settings_ignorepaths_desc"' is not assignable to parameter of type '"confirm" | "disable" | "enable" | "gobac
k" | "submit" | "sometext" | "syncrun_alreadyrunning" | "syncrun_syncingribbon" | "syncrun_step0" | "syncrun_step1" | "syncrun_step2" | ... 23
0 more ... | "syncalgov2_button_disagree"'.
ts-loader-default_e3b0c44298fc1c14
 @ ./src/main.ts 13:0-52 415:35-57
```
Seems like there's a type issue in `settings.ts` that does not seem to like the new `settings_ignorepaths` field

2024-01-01 11:46 UTC, da-the-dev requested changes

2024-01-01 11:46 UTC, da-the-dev commented on src/settings.ts
> +      .setDesc(t("settings_ignorepaths_desc"))
```
ERROR in /home/sv-cheats-1/Documents/PROJECTS/remotely-save/src/settings.ts
./src/settings.ts 1600:17-39
[tsl] ERROR in /home/sv-cheats-1/Documents/PROJECTS/remotely-save/src/settings.ts(1600,18)
      TS2345: Argument of type '"settings_ignorepaths"' is not assignable to parameter of type '"confirm" | "disable" | "enable" | "goback" | 
"submit" | "sometext" | "syncrun_alreadyrunning" | "syncrun_syncingribbon" | "syncrun_step0" | "syncrun_step1" | "syncrun_step2" | ... 230 mor
e ... | "syncalgov2_button_disagree"'.
ts-loader-default_e3b0c44298fc1c14
 @ ./src/main.ts 13:0-52 415:35-57

ERROR in /home/sv-cheats-1/Documents/PROJECTS/remotely-save/src/settings.ts
./src/settings.ts 1601:17-44
[tsl] ERROR in /home/sv-cheats-1/Documents/PROJECTS/remotely-save/src/settings.ts(1601,18)
      TS2345: Argument of type '"settings_ignorepaths_desc"' is not assignable to parameter of type '"confirm" | "disable" | "enable" | "gobac
k" | "submit" | "sometext" | "syncrun_alreadyrunning" | "syncrun_syncingribbon" | "syncrun_step0" | "syncrun_step1" | "syncrun_step2" | ... 23
0 more ... | "syncalgov2_button_disagree"'.
ts-loader-default_e3b0c44298fc1c14
 @ ./src/main.ts 13:0-52 415:35-57
```

2024-01-02 14:33 UTC, fyears commented
that's cool, but i think i will merge your pr and directly add regex support instead of raw strings

2024-01-02 14:35 UTC, fyears commented
and why they are ignored?

[".obsidian/workspace.json", ".obsidian/workspace-mobile.json", ".obsidian/community-plugins.json"]

if users want to sync the .obsidian folder, i think they want to sync these files too?

2024-01-03 15:36 UTC, merged

2024-01-05 11:57 UTC, ras0q commented
Sorry for late reply! Thank you for merging!
I agree with regex support, too.

Obsidian [official document](https://help.obsidian.md/Files+and+folders/How+Obsidian+stores+data#Vault+settings) notes that the workspace files should be added to `.gitignore` as they are easy to conflicts, and I think this plugin should also ignore these files.
And in my usecases, I use different community plugins between PC and mobiles, so I added also `community-plugins.json` by default.